# Generated by Django 4.2.7 on 2023-11-07 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('Entrada', 'ENTRADA'), ('Saída', 'SAIDA')], max_length=7, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
            ],
        ),
    ]
